[metadata]
addr = 0x88623ec
size = 0xb8
last_change = 2023-11-15T18:10:58.227927Z

[header]
last_change = 2023-11-15T18:08:53.988622Z
name = "CRunningScript::Init"
addr = 0x88623ec
type = "int"

[header.args.0]
offset = 0x0
name = "a1"
type = "int"
size = 0x4
