[metadata]
addr = 0x887f3c0
size = 0x30
last_change = 2023-11-15T18:10:09.195646Z

[header]
last_change = 2023-11-15T18:09:19.107886Z
name = "CStreaming::UnregisterInstance"
addr = 0x887f3c0
type = "int"

[header.args.0]
offset = 0x0
name = "a1"
type = "int"
size = 0x4
