[metadata]
addr = 0x88713b4
size = 0x1c
last_change = 2023-11-15T18:09:24.561177Z

[header]
last_change = 2023-11-15T18:09:19.018349Z
name = "CFileMgr::OpenFile"
addr = 0x88713b4
type = "int *"

[header.args.0]
offset = 0x0
name = "a1"
type = "int"
size = 0x4
