[metadata]
addr = 0x8883c6c
size = 1
last_change = 2023-11-20T18:14:13.207413Z

[header]
last_change = 2023-11-20T18:13:58.019179Z
name = "Command_ADD_SET_PIECE_WHEN_WANTED_IN_2D_AREA_SPAWN_AT_TARGET_AND_AT_TARGET"
addr = 0x8883c6c
