[metadata]
addr = 0x88c66c8
size = 0x1a4
last_change = 2023-11-15T18:12:55.083098Z

[header]
last_change = 2023-11-15T18:08:56.313272Z
name = "cAudioManager::ProcessRainOnVehicle"
addr = 0x88c66c8
type = "void"

[header.args.0]
offset = 0x0
name = "a1"
type = "int"
size = 0x4

[header.args.1]
offset = 0x1
name = "a2"
type = "int"
size = 0x4
