[metadata]
addr = 0x890043c
size = 0xad8

[header]
name = "CParticle::AddParticle2"
addr = 0x890043c
type = "int"

[header.args.0]
offset = 0x0
name = "a1"
type = "int"
size = 0x4

[header.args.1]
offset = 0x1
name = "a2"
type = "_DWORD *"
size = 0x4

[header.args.2]
offset = 0x2
name = "$A2"
type = "int"
size = 0x4

[header.args.3]
offset = 0x3
name = "a4"
type = "float"
size = 0x4

[header.args.4]
offset = 0x4
name = "a5"
type = "int"
size = 0x4

[header.args.5]
offset = 0x5
name = "a6"
type = "int"
size = 0x4

[header.args.6]
offset = 0x6
name = "a7"
type = "int"
size = 0x4

[header.args.7]
offset = 0x7
name = "a8"
type = "short"
size = 0x2

[header.args.8]
offset = 0x8
name = "a9"
type = "int"
size = 0x4

[header.args.9]
offset = 0x9
name = "a10"
type = "int"
size = 0x4
