[metadata]
addr = 0x894553c
size = 0x174
last_change = 2023-11-15T18:11:06.396805Z

[header]
last_change = 2023-11-15T18:09:21.170216Z
name = "CVisibilityComponents::RenderVehicleHiDetailAlphaCB"
addr = 0x894553c
type = "int"

[header.args.0]
offset = 0x0
name = "a1"
type = "int"
size = 0x4

[header.args.1]
offset = 0x1
name = "a2"
type = "int"
size = 0x4

[header.args.2]
offset = 0x2
name = "a3"
type = "int"
size = 0x4
