[metadata]
addr = 0x8946130
size = 0x28
last_change = 2023-11-15T18:12:46.617705Z

[header]
last_change = 2023-11-15T18:09:50.070780Z
name = "CVisibilityComponents::SetElementRenderCallback"
addr = 0x8946130
type = "void"

[header.args.0]
offset = 0x0
name = "a1"
type = "int"
size = 0x4

[header.args.1]
offset = 0x1
name = "a2"
type = "int (__fastcall *)(int)"
size = 0x4
