[metadata]
addr = 0x894599c
size = 0xe0
last_change = 2023-11-15T18:10:27.351229Z

[header]
last_change = 2023-11-15T18:09:48.524818Z
name = "CVisibilityComponents::RenderVehicleRotorAlphaCB"
addr = 0x894599c
type = "int"

[header.args.0]
offset = 0x0
name = "a1"
type = "int"
size = 0x4

[header.args.1]
offset = 0x1
name = "a2"
type = "int"
size = 0x4

[header.args.2]
offset = 0x2
name = "a3"
type = "int"
size = 0x4
