[metadata]
addr = 0x8976188
size = 0x128
last_change = 2023-11-18T16:40:34.351792Z

[header]
name = "Command_UNKNOWN_EMPIRE_DISPLAY_COMMAND_8527_STORE_TO"
addr = 0x8976188

[stack_vars.-0x2c]
offset = -44
name = "local_2c"
type = "undefined *"
size = 0x4
addr = 0x8976188

[stack_vars.-0x28]
offset = -40
name = "local_28"
type = "int"
size = 0x4
addr = 0x8976188

[stack_vars.-0x30]
offset = -48
name = "auStack48"
type = "undefined[4]"
size = 0x4
addr = 0x8976188
