[metadata]
addr = 0x8976000
size = 1
last_change = 2023-11-20T18:14:13.207413Z

[header]
last_change = 2023-11-20T18:13:58.019179Z
name = "Command_SET_DRAWN_DISPLAY_BACKGROUND_COLOR_ID_RGB_RED_RGB_GREEN_RGB_BLUE_OPACITY"
addr = 0x8976000
