[metadata]
addr = 0x08a13e58
last_change = 2023-11-20T18:14:13.207413Z

[header]
last_change = 2023-11-20T18:13:58.019179Z
name = "Command_CREATE_PROJECTILE_WEAPON_TYPE_COORDS_POWER_PED_HANDLE_FLAG_STORE_TO"
addr = 0x08a13e58
