[metadata]
addr = 0x8a8d438
size = 0x68
last_change = 2023-11-18T16:35:09.931038Z

[header]
name = "Command_UNKNOWN_AUDIO_COMMAND_8451_POINT"
addr = 0x8a8d438

[stack_vars.-0x1c]
offset = -28
name = "local_1c"
type = "int"
size = 0x4
addr = 0x8a8d438

[stack_vars.-0x20]
offset = -32
name = "local_20"
type = "int"
size = 0x4
addr = 0x8a8d438

[stack_vars.-0x18]
offset = -24
name = "local_18"
type = "int"
size = 0x4
addr = 0x8a8d438
