[metadata]
addr = 0x8a8d3c8
size = 0x70
last_change = 2023-11-18T16:35:09.610042Z

[header]
name = "Command_UNKNOWN_AUDIO_COMMAND_7532_POINT_VALUES"
addr = 0x8a8d3c8

[stack_vars.-0x1c]
offset = -28
name = "local_1c"
type = "int"
size = 0x4
addr = 0x8a8d3c8

[stack_vars.-0x20]
offset = -32
name = "local_20"
type = "int"
size = 0x4
addr = 0x8a8d3c8

[stack_vars.-0x18]
offset = -24
name = "local_18"
type = "int"
size = 0x4
addr = 0x8a8d3c8
