[metadata]
addr = 0x8a9260c
size = 0x140
last_change = 2023-11-18T16:34:14.643974Z

[header]
name = "Command_GET_CLOSEST_CAR_NODE_WITH_HEADING_STORE_TO_HEADING_TO"
addr = 0x8a9260c

[stack_vars.-0x3c]
offset = -60
name = "local_3c"
type = "int"
size = 0x4
addr = 0x8a9260c

[stack_vars.-0x40]
offset = -64
name = "local_40"
type = "int"
size = 0x4
addr = 0x8a9260c

[stack_vars.-0x30]
offset = -48
name = "local_30"
type = "int"
size = 0x4
addr = 0x8a9260c

[stack_vars.-0x38]
offset = -56
name = "local_38"
type = "float"
size = 0x4
addr = 0x8a9260c

[stack_vars.-0x28]
offset = -40
name = "local_28"
type = "int"
size = 0x4
addr = 0x8a9260c

[stack_vars.-0x2c]
offset = -44
name = "local_2c"
type = "int"
size = 0x4
addr = 0x8a9260c
