[metadata]
addr = 0x8aa1ba4
size = 0x124
last_change = 2023-11-15T18:14:13.207413Z

[header]
last_change = 2023-11-15T18:13:58.019179Z
name = "CVehicleModelInfo::SetVehicleColour"
addr = 0x8aa1ba4
type = "void"

[header.args.0]
offset = 0x0
name = "a1"
type = "int"
size = 0x4

[header.args.1]
offset = 0x1
name = "a2"
type = "char *"
size = 0x4

[header.args.2]
offset = 0x2
name = "a3"
type = "char *"
size = 0x4
