[metadata]
addr = 0x8ac4318
size = 0xde4
last_change = 2023-11-15T18:11:36.151776Z

[header]
last_change = 2023-11-15T18:10:21.385800Z
name = "CGame::Process"
addr = 0x8ac4318
type = "void"

[stack_vars.-0x78]
offset = 0x10
name = "v154"
type = "int"
size = 0x4
addr = 0x8ac4318

[stack_vars.-0x74]
offset = 0x14
name = "v155"
type = "int"
size = 0x4
addr = 0x8ac4318

[stack_vars.-0x70]
offset = 0x18
name = "v156"
type = "int"
size = 0x4
addr = 0x8ac4318

[stack_vars.-0x6c]
offset = 0x1c
name = "v157"
type = "int"
size = 0x4
addr = 0x8ac4318

[stack_vars.-0x68]
offset = 0x20
name = "v158"
type = "int"
size = 0x4
addr = 0x8ac4318

[stack_vars.-0x64]
offset = 0x24
name = "v159"
type = "int"
size = 0x4
addr = 0x8ac4318

[stack_vars.-0x60]
offset = 0x28
name = "v160"
type = "int"
size = 0x4
addr = 0x8ac4318

[stack_vars.-0x5c]
offset = 0x2c
name = "v161"
type = "int"
size = 0x4
addr = 0x8ac4318

[stack_vars.-0x58]
offset = 0x30
name = "v162"
type = "char[8]"
size = 0x8
addr = 0x8ac4318

[stack_vars.-0x50]
offset = 0x38
name = "v163"
type = "char[4]"
size = 0x4
addr = 0x8ac4318

[stack_vars.-0x4c]
offset = 0x3c
name = "v164"
type = "char[4]"
size = 0x4
addr = 0x8ac4318

[stack_vars.-0x48]
offset = 0x40
name = "v165"
type = "char[8]"
size = 0x8
addr = 0x8ac4318

[stack_vars.-0x40]
offset = 0x48
name = "v166"
type = "char[4]"
size = 0x4
addr = 0x8ac4318

[stack_vars.-0x3c]
offset = 0x4c
name = "v167"
type = "char[4]"
size = 0x4
addr = 0x8ac4318

[stack_vars.-0x38]
offset = 0x50
name = "v168"
type = "char[8]"
size = 0x8
addr = 0x8ac4318

[stack_vars.-0x30]
offset = 0x58
name = "v169"
type = "char[4]"
size = 0x4
addr = 0x8ac4318

[stack_vars.-0x2c]
offset = 0x5c
name = "v170"
type = "char[4]"
size = 0x4
addr = 0x8ac4318

[stack_vars.-0x28]
offset = 0x60
name = "v171"
type = "char[8]"
size = 0x8
addr = 0x8ac4318

[stack_vars.-0x20]
offset = 0x68
name = "v172"
type = "char[4]"
size = 0x4
addr = 0x8ac4318

[stack_vars.-0x1c]
offset = 0x6c
name = "v173"
type = "char[4]"
size = 0x4
addr = 0x8ac4318
