[metadata]
addr = 0x8ad3258
size = 0x28
last_change = 2023-11-15T18:11:28.159512Z

[header]
last_change = 2023-11-15T18:10:21.928216Z
name = "CStreaming::RequestModel"
addr = 0x8ad3258
type = "_DWORD *"

[header.args.0]
offset = 0x0
name = "a1"
type = "int"
size = 0x4

[header.args.1]
offset = 0x1
name = "a2"
type = "char"
size = 0x1

[header.args.2]
offset = 0x2
name = "a3"
type = "int"
size = 0x4
