[metadata]
addr = 0x8ad3610
size = 0x24
last_change = 2023-11-15T18:12:38.822156Z

[header]
last_change = 2023-11-15T18:11:53.419587Z
name = "CStreaming::LoadAllRequestedModels"
addr = 0x8ad3610
type = "int"

[header.args.0]
offset = 0x0
name = "a1"
type = "unsigned char"
size = 0x1
