[metadata]
addr = 0x8aeaaec
size = 1
last_change = 2023-11-20T18:14:13.207413Z

[header]
last_change = 2023-11-20T18:13:58.019179Z
name = "Command_UNKNOWN_CAR_GET_COMMAND_8218_STORE_VALUES_TO"
addr = 0x8aeaaec
