[metadata]
addr = 0x8af43ac
size = 0xb0
last_change = 2023-11-15T18:10:58.777760Z

[header]
last_change = 2023-11-15T18:10:23.155210Z
name = "CSprite2d::AddToBuffer"
addr = 0x8af43ac
type = "int"

[header.args.0]
offset = 0x0
name = "a1"
type = "float *"
size = 0x4

[header.args.1]
offset = 0x1
name = "a2"
type = "char *"
size = 0x4

[header.args.2]
offset = 0x2
name = "a3"
type = "float"
size = 0x4

[header.args.3]
offset = 0x3
name = "a4"
type = "float"
size = 0x4

[header.args.4]
offset = 0x4
name = "a5"
type = "float"
size = 0x4

[header.args.5]
offset = 0x5
name = "a6"
type = "float"
size = 0x4

[header.args.6]
offset = 0x6
name = "a7"
type = "float"
size = 0x4

[header.args.7]
offset = 0x7
name = "a8"
type = "float"
size = 0x4

[header.args.8]
offset = 0x8
name = "a9"
type = "float"
size = 0x4

[header.args.9]
offset = 0x9
name = "a10"
type = "float"
size = 0x4
