[metadata]
addr = 0x8af1804
size = 1
last_change = 2023-11-20T18:14:13.207413Z

[header]
last_change = 2023-11-20T18:13:58.019179Z
name = "Command_PRINT_WITH_NUMBER_NOW_DONT_ADD_TO_BRIEF_ARRAY_NUMBER_TIME_FLAG"
addr = 0x8af1804
