[metadata]
addr = 0x8b0d8ec
size = 0xc
last_change = 2023-11-15T18:11:15.043877Z

[header]
last_change = 2023-11-15T18:08:29.063003Z
name = "CDamageManager::SetWheelStatus"
addr = 0x8b0d8ec
type = "void"

[header.args.0]
offset = 0x0
name = "a1"
type = "int"
size = 0x4

[header.args.1]
offset = 0x1
name = "a2"
type = "int"
size = 0x4

[header.args.2]
offset = 0x2
name = "a3"
type = "char"
size = 0x1
