[metadata]
addr = 0x8b0c4a8
size = 0x24
last_change = 2023-11-15T18:08:41.016289Z

[header]
last_change = 2023-11-15T18:08:28.676202Z
name = "CRGBA::CRGBA_0"
addr = 0x8b0c4a8
type = "void"

[header.args.0]
offset = 0x0
name = "a1"
type = "char *"
size = 0x4
