[metadata]
addr = 0x8b1e19c
size = 1
last_change = 2023-11-20T18:14:13.207413Z

[header]
last_change = 2023-11-20T18:13:58.019179Z
name = "Command_DRAW_CHECKPOINT_WITH_ALPHA_COORDS_COORDS_COLOUR_RADIUS"
addr = 0x8b1e19c
