[metadata]
addr = 0x8b2caf4
last_change = 2023-11-20T18:14:13.207413Z

[header]
last_change = 2023-11-20T18:13:58.019179Z
name = "Command_SET_CHAR_CAN_BE_DAMAGED_BY_MEMBERS_OF_GANG_GANG_ID_UNK3"
addr = 0x8b2caf4
