[metadata]
addr = 0x08b2e1a0
last_change = 2023-11-20T18:14:13.207413Z

[header]
last_change = 2023-11-20T18:13:58.019179Z
name = "Command_GET_RANDOM_ICE_CREAM_CUSTOMER_IN_AREA_FROM_TO_CIVILIAN_GANG_CRIMINAL/PROSTITUTE_STORE_TO"
addr = 0x08b2e1a0
