[metadata]
addr = 0x8b2f350
size = 1
last_change = 2023-11-20T18:14:13.207413Z

[header]
last_change = 2023-11-20T18:13:58.019179Z
name = "Command_GET_RANDOM_CHAR_OF_SPECIFIED_MODEL_IN_AREA_3D_TO_MODEL_OR_STORE_TO"
addr = 0x8b2f350
