[metadata]
addr = 0x8b2ae40
size = 1
last_change = 2023-11-20T18:14:13.207413Z

[header]
last_change = 2023-11-20T18:13:58.019179Z
name = "Command_WARP_CHAR_INTO_CAR_AS_PASSENGER_CAR_SEAT"
addr = 0x8b2ae40
