[metadata]
addr = 0x8b458a8
size = 0x904
last_change = 2023-11-15T18:07:07.224546Z

[header]
last_change = 2023-11-15T18:07:07.168544Z
name = "CCarCtrl::PossiblyRemoveVehicle"
addr = 0x8b458a8
type = "int"

[stack_vars.-0xc0]
offset = 0x0
name = "v36"
type = "float"
size = 0x4
addr = 0x8b458a8

[stack_vars.-0xbc]
offset = 0x4
name = "v37"
type = "float"
size = 0x4
addr = 0x8b458a8

[stack_vars.-0xb0]
offset = 0x10
name = "v38"
type = "char[16]"
size = 0x10
addr = 0x8b458a8

[stack_vars.-0xa0]
offset = 0x20
name = "v39"
type = "char"
size = 0x1
addr = 0x8b458a8

[stack_vars.-0x90]
offset = 0x30
name = "v40"
type = "char"
size = 0x1
addr = 0x8b458a8

[stack_vars.-0x80]
offset = 0x40
name = "v41"
type = "char"
size = 0x1
addr = 0x8b458a8

[stack_vars.-0x40]
offset = 0x80
name = "v42"
type = "int"
size = 0x4
addr = 0x8b458a8

[stack_vars.-0x3c]
offset = 0x84
name = "v43"
type = "int"
size = 0x4
addr = 0x8b458a8

[stack_vars.-0x38]
offset = 0x88
name = "v44"
type = "int"
size = 0x4
addr = 0x8b458a8

[stack_vars.-0x34]
offset = 0x8c
name = "k"
type = "char"
size = 0x1
addr = 0x8b458a8

[stack_vars.-0x33]
offset = 0x8d
name = "v46"
type = "char"
size = 0x1
addr = 0x8b458a8

[stack_vars.-0x28]
offset = 0x98
name = "v47"
type = "int"
size = 0x4
addr = 0x8b458a8

[header.args.0]
offset = 0x0
name = "a1"
type = "unsigned int"
size = 0x4
